/**
 * Help content — the single source for BOTH the editor's ? Help panel and
 * `docs/GUIDE.md` (generated by `npm run docs:guide`). Everything else in
 * `docs/` is hand-synced and drifts; this must not, so never write the guide by
 * hand — edit here and regenerate.
 *
 * Concepts explain the model. Recipes are the short paths through it. Neither
 * restates the option list — `docs/tools/reference.html` already does that.
 */

export interface HelpTopic {
  id: string;
  title: string;
  /** Paragraphs. `code` spans are written with backticks and rendered as such. */
  body: string[];
  /** Ordered steps, for recipes. */
  steps?: string[];
}

export const HELP_CONCEPTS: HelpTopic[] = [
  {
    id: 'cascade',
    title: 'Why a setting sometimes does nothing',
    body: [
      'Almost every visual option can be set at several levels, and the most specific one wins. The order is: this device → this device type → this room → this view → the whole card → the built-in default.',
      'That is why a per-device colour beats a room colour, and why a card-wide `tile_style` beats the per-profile defaults that `smart_tile_styles` turns on — the card-wide value is more specific than a built-in default, so smart styles never get a look in. Set styles per device type instead of card-wide if you want both.',
      'For blocks there is one extra rung: a saved custom style\'s own layout sits above the room and card-wide values, since choosing a saved look is more deliberate than leaving the global default in place.',
      'The editor flags the common cases for you — see Conflicts.',
    ],
  },
  {
    id: 'design-scopes',
    title: 'Where a setting lives',
    body: [
      'Everything about how the card looks is in one tab: **Design**. It is *scope-first* — you pick **where** you are editing, and the same control list redraws for that layer. Global, a view, a room, a device type, or one device.',
      'Pick the scope in the map at the top. Devices are grouped by room, type or integration; room and type headings are clickable because they are layers you can style, while an integration is only a way to find a device. The number on a chip is how many settings that layer overrides, so you can see where customisation lives without opening everything.',
      'Every control says where its value is coming from — **set here**, with a ↺ to drop it, or **from Room · Kitchen** / **from Card**. Most specific wins, always.',
      'What you can set depends on the layer, and the tab says why. There are three groups. **Tile** settings — theme, colour, tile style, blocks, chips, graphs, energy window — can be set anywhere: device, type, room, view, card. **Container** settings — columns and tile size — stop at the room, because a grid needs something to hold it and one device has no column count. **Card chrome** — the header, the card surface, typography — only a view or the card can set, because a room does not contain the card\'s header.',
      'Two scopes also hold settings with no ladder under them at all. Global has the theme picker, chips & metrics, tiles, the sensor-chip groups, and the card\'s own header and type. A room has **Room chrome** — the room block\'s backdrop photo, tile gap, header colours, borders, per-room header chips and button shapes — things that exist exactly once per room.',
      'A shortcut worth knowing: in the card editor, tapping a device tile in the **live preview** jumps straight to that device\'s scope in Design — same landing as the ✎ button in Rooms & devices. Buttons and sliders on the tile still work normally, so you can test controls in the preview too.',
    ],
  },
  {
    id: 'content-defaults',
    title: 'Global defaults vs. per-room overrides',
    body: [
      'The **Chips & metrics** section in Design (at Global scope) sets three things card-wide: which chips each room header shows, which window the energy readout totals (Total / Today / Week / Month), and which sensor chips appear on tiles. Treat it as the first stop — decide what data is on show, then style it.',
      'These are *defaults*. Every room and device inherits them, but any room or device can override any of them — by picking that room or device as the scope in Design — and the moment it does, it stops listening to the global. A global toggle only moves scopes that are still inheriting: turning a chip on globally will **not** turn it on in a room that has set its own chips, and turning it off will not turn it off there.',
      'Each picker tells you which state it is in. **Inheriting from …** means a global change still reaches it; **Custom selection** means it is pinned to its own value. Setting a room or device to an empty selection is itself a custom choice ("show none"), not the same as inheriting.',
      'To hand control back to the global default, use that scope\'s reset — `↺ Default` for room header chips, `↺ Inherit` for the chip pickers. Room header chips resolve room → global → built-in; energy and sensor chips also allow a per-device override (and, for sensor chips, a per-type one) in front of the room.',
    ],
  },
  {
    id: 'discovery',
    title: 'Discovery: what the card looks at',
    body: [
      '**Shelly mode** (the default) keeps only Shelly and BTHome devices. Most "my device is missing" reports are simply this.',
      '**Universal mode** discovers every device in Home Assistant, then narrows it three ways: a *scope* (real devices / controllable only / everything), a built-in deny-list of things that are not really devices (phones, browsers, routers, the supervisor), and your own Hide integrations / Hide entity types lists on top.',
      'The two hide lists resolve in opposite directions, which is worth knowing: for domains, excluding wins; for integrations, `include_integrations` is a force-include that overrides the deny-list. That is how you bring one router back without unhiding all of them.',
      'Shelly devices keep their full-fidelity detection in universal mode — model, generation, per-channel merging — so switching modes never downgrades them.',
    ],
  },
  {
    id: 'profiles',
    title: 'Profiles, tile styles and blocks are three different things',
    body: [
      'A **profile** is what the card decides a device *is* — relay, dimmer, cover, sensor, input, and so on — from its entities, refined by Shelly model. It drives the badge, the default chips and the default layout. You can override it per device if the guess is wrong.',
      'A **tile style** is how that device is drawn: the adaptive block tile (`default`), or a purpose-built one (power monitor, light control, climate dial, cover, sensor card, input keypad, scene button).',
      'A **block** is one row of content inside the `default` style only — name row, chips, graph, dimmer, cover controls, and so on. Setting blocks on a device that renders as a power monitor does nothing, because that style does not use blocks; use its Elements instead.',
    ],
  },
  {
    id: 'hiding',
    title: 'Blocks, elements and chips — which one hides what',
    body: [
      '**Blocks** reorder and hide the parts of the `default` tile. **Elements** show and hide the parts of every other style (its toggle, graph, secondary readings…) — and carry the odd placement choice, like "Chips in the name row" on the power-monitor and sensor styles, which moves the secondary readings up beside the device name. **Sensor chips** choose which measurements appear as little pills, in any style.',
      'The editor only offers what applies: pick a power-monitor style and the block grid disappears in favour of that style\'s elements.',
      'Design narrows to whatever scope you pick: choose one device and it offers only the chips that device can produce and the blocks it can render — an i4 offers only the chips it can actually produce and the blocks it can actually render. Flip **All options** at the top of that panel if you want the full surface back.',
    ],
  },
  {
    id: 'inputs',
    title: 'Input devices have no output',
    body: [
      'An input is one of two things, and the card reads which from Home Assistant. A **button** input is momentary — it reports presses (single, double, long) on an `event` entity, and its row shows the last press and how long ago. A **switch** input is steady — it reports its position on a `binary_sensor`, and its row shows an ON/OFF pill. Relays have inputs too: a Plus 1PM\'s "Input 0" is the wall switch wired to it.',
      'An input that is wired to an output on its own device (`input_0` → `switch_0`) needs no setup: tapping its row toggles that output, and the row lights with the output\'s state. That is the one thing the physical input does that Home Assistant can replay.',
      'A Shelly i3, i4 or UNI has no output of its own — it reports presses and controls nothing by itself, so the card cannot "push" a channel for you. What it can do is run the same thing the physical button runs. In Design, pick the device as the scope and use **Input actions**: give a channel an action and its row becomes a key — tap toggles an entity or runs a script, hold dims the target light (alternating direction each hold, like a wall dimmer), double-tap runs a second action, and an optional dropdown exposes a `select` entity such as WLED presets.',
      'A key that toggles something lights up while that thing is on, so the tile doubles as a status display. A key that runs a script stays neutral — the card cannot know a script\'s state and will not pretend to. Channels you have not wired stay as status rows; tapping one opens its press history.',
    ],
  },
  {
    id: 'lights',
    title: 'What counts as a light',
    body: [
      'The **Lights** header chip counts `light` entities that are on. A relay or plug wired to a lamp is a `switch` as far as Home Assistant is concerned — it has no way to know what is on the other end of the wire, and neither does the card.',
      'You do. Label those devices in Home Assistant (Settings → Areas & labels), then tick the label under **Header → What counts as a light**. Every `switch` on a labelled device is counted from then on. The picker only offers labels that exist on your devices, with how many carry each.',
      'For the stragglers a label does not cover, name entities directly in the same panel. A device caught by both routes is still counted once.',
    ],
  },
  {
    id: 'themes',
    title: 'Themes and colours',
    body: [
      'The **theme** is authoritative: every colour comes from the preset you pick. The `style` block holds only colours you deliberately changed on top.',
      '**Follow HA** is the exception: instead of a palette it points every colour at Home Assistant’s own theme variables, so the card matches whatever HA theme is active and follows it into light or dark. Available per card, per view and per room like any other theme.',
      'Picking a theme clears those overrides, so the editor offers to save your current colours first — they come back under a ★ Saved entry in the theme picker.',
      'Older configs wrote the whole palette into `style`, which shadowed the theme and made switching it do nothing. Those are migrated automatically on load: a palette that exactly matches a preset collapses back to the theme name, while a partial palette is left alone as the genuine override it is.',
      'A **view** and a **room** can each take a theme of their own, resolved room → view → card. A view theme repaints the whole card, header included, while that view is showing, and outranks the colours in `style`. A room theme repaints what the room contains — its block background, tiles, text, accent and its own header — but not the card header, which no room encloses; the room\'s individual colour fields still override it key by key.',
    ],
  },
  {
    id: 'energy',
    title: 'Energy: totals versus windows',
    body: [
      'By default the energy chip shows a device\'s lifetime total, straight from its own sensor. Switch it to Today, This week or This month and the card asks the recorder for consumption over that window instead — no helper entities required.',
      'A device with several energy sensors (a Pro 4PM has one per channel) is summed, not sampled, so a multi-channel device is not under-counted.',
      'If you already keep a Utility Meter for a device, point `energy_entity` at it. That replaces the device\'s own energy chips everywhere — tile, room total and header — so the override never sits next to the raw numbers it stands in for.',
    ],
  },
  {
    id: 'attention',
    title: 'Needs attention',
    body: [
      'A fifty-device dashboard hides its own problems — three offline devices among fifty tiles is something you scroll past. The summary above the rooms answers the question the tiles cannot: which ones.',
      'It lists offline devices, firing alerts, flat batteries and pending updates, worst first. Each row opens that device. It is invisible when nothing qualifies, so it costs nothing on a good day.',
      'An offline device is reported as offline and nothing else — its last alert reading is stale, not news.',
      'The firmware block groups the fleet by version and marks the newest, so a device left behind on an old build is obvious. It appears only when more than one version is running.',
      '**Beta firmware does not count as an update.** A Shelly exposes a `beta_firmware` entity that is on nearly permanently — on one real fleet that was 21 of 25 "available updates". Turn on `include_beta_updates` if you actually run betas.',
    ],
  },
  {
    id: 'conflicts',
    title: 'The Conflicts panel',
    body: [
      'When a setting is overridden or ignored, a badge appears above the editor tabs. It exists because the failure is otherwise silent — the option is valid, it just never applies.',
      'It watches for: a theme its `style` block contradicts, smart tile styles masked by a card-wide style, discovery filters set while in Shelly mode, an integration or domain in both the include and exclude lists, the Native controls block with the feature switched off, a saved style that no longer exists, styling attached to a device or room that is gone, input actions pointing at missing entities, hide lists that hide absolutely everything, keys the card does not read at all, and an input action whose channel has been renamed out from under it.',
      'Nothing there is an error — a stale block is harmless. It is a list of things that are not doing what they look like they are doing.',
    ],
  },
];

export const HELP_RECIPES: HelpTopic[] = [
  {
    id: 'first-run',
    title: 'Start from scratch',
    body: ['A new card discovers your Shelly and BTHome devices and groups them by room. Everything below is optional.'],
    steps: [
      'Edit dashboard → Add card → HA Device Dashboard.',
      'To include non-Shelly devices: Rooms & devices → Discovery → Universal, then pick a scope. Start with "Real devices".',
      'Set the look once under ◆ Defaults (theme, columns, tile size).',
      'Use ◆ Defaults → Reset look if you want the factory appearance back without losing rooms, devices or actions.',
    ],
  },
  {
    id: 'confirm-off',
    title: 'Guard a device you must not switch off by accident',
    body: [
      'A freezer, a server, the router, the heating — a mis-tap costs you something real. Turning the device ON is never confirmed, so the guard only slows you down in the direction that hurts.',
      'It is set per device on purpose. Two identical plugs in the same room can disagree, which is what you want: arming a whole type or room would put the prompt in front of you constantly and train you to tap straight through it.',
    ],
    steps: [
      'Design → pick the device in the scope picker.',
      'Under "Safety — this device only", turn on "Ask before turning off".',
      'Tapping OFF now opens a prompt. Cancel is the wide button; the red "Turn off" is the narrow one.',
      'It covers every on/off the card draws for that device, including the per-channel relay rows and the detail sheet. It cannot cover a control drawn by Home Assistant itself under Native controls.',
    ],
  },
  {
    id: 'extra-card-layout',
    title: 'Show an embedded card only sometimes, or put two side by side',
    body: [
      'Cards you embed under Extra cards are rendered by Home Assistant itself, so anything a card can normally do in a dashboard it can do here.',
    ],
    steps: [
      'Extra cards → pick the placement (header, footer or a room) → Add card.',
      'The Preview under the YAML draws the card as you type, exactly as the dashboard will — including an error card if the config is wrong.',
      'Header and footer cards can differ per view: set "Applies to" to a view and that view gets its own list, replacing the card-wide one. An empty list on a view means no cards there at all. "Use the card-wide list" clears the override.',
      'Use ▲ ▼ on a row to reorder.',
      'For a room, "Where in the room" puts the cards above the tiles (a strip) or among them (each card takes a tile\'s place). In the grid, grid_options.columns counts tiles rather than twelfths.',
      'Set Look to "Match this card" and embedded cards take the dashboard\'s background, border, radius, text and accent instead of Home Assistant\'s theme — so they sit in the card rather than on it. A card that hard-codes its own colours keeps them.',
      'To show it conditionally, give the card a `visibility:` block — the same state, user and screen conditions a dashboard card takes. A card hidden by its condition leaves no gap.',
      'To make it narrower, give it `grid_options: {columns: 6}` — the strip is twelve columns wide, so two sixes sit side by side. Leave `grid_options` out for full width.',
      '`rows` sets a minimum height; the strip grows to fit its content rather than clipping.',
    ],
  },
  {
    id: 'hide-onoff',
    title: 'Hide the on/off button on a tile',
    body: ['For a device you only want to watch, or one whose switching belongs somewhere else.'],
    steps: [
      'Design → pick the scope (device, type, room, view or Global).',
      'Open the tile style block and untick "On/off button".',
      'Available on the default, Power and Light tile styles — the three that draw a primary on/off button.',
      'The device can still be switched from its detail sheet; this hides the button on the tile.',
    ],
  },
  {
    id: 'quiet',
    title: 'Quieten a noisy universal dashboard',
    body: ['Universal mode surfaces everything, including things that are not really devices. Two lists trim it.'],
    steps: [
      'Rooms & devices → Discovery.',
      'Open Hide integrations and tick what you do not want. Use Hide all, then untick the few you do want.',
      'Do the same in Hide entity types for whole domains such as update or camera.',
      'Still too much? Drop the scope from Everything to Real devices.',
    ],
  },
  {
    id: 'cloud-import',
    title: 'Import your Shelly app setup',
    body: ['Coming from the Shelly app? The card can pull each room\'s photo and the official product image for every device from your Shelly Cloud account. The auth key is used for the one fetch and never saved; imported images stay hosted on Shelly\'s cloud.'],
    steps: [
      'Get your key: control.shelly.cloud → user settings → Authorization cloud key. Note the server shown next to it.',
      'Rooms & devices → Import from Shelly Cloud → paste both → Fetch my Shelly setup.',
      'Pair any cloud rooms that did not auto-match with a room here (name matching ignores accents).',
      'Pick what to import — room photos, product images on tiles, full-size vs thumbnails — and Apply.',
      'A custom room photo\'s cloud URL is unlisted but not private. Swap in a /local/… photo later if that matters.',
      'To invalidate a key you have shared or leaked, change your Shelly account password — the key only rotates with it.',
    ],
  },
  {
    id: 'room-style',
    title: 'Give one room its own look',
    body: ['Room styling is keyed by the room name, so renaming an area in Home Assistant orphans it — the Conflicts panel will tell you.'],
    steps: [
      'Design → Scope → pick the room (or expand it to reach one device).',
      'Pick the room, then set its colours, tile style, columns or backdrop.',
      'Anything you leave alone keeps inheriting from the card-wide settings.',
    ],
  },
  {
    id: 'wire-input',
    title: 'Make an i3 / i4 button control a light',
    body: [
      'The card only reacts to taps on the screen — it cannot give the wall button a job. The physical press is handled by the Shelly\'s own action/script or by a Home Assistant automation, and which of those you have decides the setup.',
      'A relay with its own output (a 1PM, a Dimmer) needs none of this: its input toggles its own relay by default.',
    ],
    steps: [
      'Design → Scope → expand a room → pick the switch → Input actions.',
      'No automation, Shelly handles the wall itself: choose "Toggle entity" and enter the light, e.g. light.hall. Several entities work too, comma separated.',
      'An automation already reacts to the button (a Shelly "Button N single push" device trigger): choose "Replay the press" instead — the row fires the same event the wall does, the automation runs, and nothing is configured twice. Hold and double tap can replay long and double pushes the same way.',
      'Set "On hold" to "Dim the light while held" for a dimmer. Hold brightens, release, hold again darkens.',
      'Optionally set a double-tap action, or point the Dropdown field at a select entity such as select.wled_preset.',
      'If the switch does not show a keypad, its tile style is set elsewhere — set Device type "Input" to the Inputs style, or use the per-type panel.',
    ],
  },
  {
    id: 'extra-sensors',
    title: 'Show a reading from another device on a tile',
    body: ['A Wall Display XL has a light sensor but no temperature or humidity sensor; the room\'s readings come from a BLU H&T beside it. Borrow them and the tile shows them as its own — chips, graphs, gauge rings and the detail sheet included.'],
    steps: [
      'Design → Scope → expand the room → pick the device → Extra sensors.',
      'Search for the sensor entity on the other device (sensor.blu_ht_temperature, say) and pick it. Several work.',
      'The other device keeps showing the reading too, and a borrowed sensor never decides whether this device counts as online.',
    ],
  },
  {
    id: 'colours',
    title: 'Roll a colour scheme',
    body: ['The theme picker can roll a look for you, and keep the ones you like as named palettes.'],
    steps: [
      'Design → Colour theme. Global sets the card; pick a view, room, type or device first to set one just there.',
      '🎲 Random lands on one of the built-in presets.',
      '✨ Surprise me generates a palette from a random hue instead. Every text colour is contrast-checked against the surface behind it, so a roll is never unreadable.',
      '💾 Save keeps the colours you are looking at under a name — including a preset you have tweaked. Saved palettes appear as ★ swatches in the picker; ✕ on a swatch forgets it.',
      'Rolling stashes the current colours as “Before roll” first, and picking a preset stashes them as “Before theme change”, so neither is a one-way door.',
    ],
  },
  {
    id: 'snapshots',
    title: 'Save a setup you can get back',
    body: ['Snapshots capture the whole card config. Slots live in this browser; the file export is what moves between devices.'],
    steps: [
      'Toolbar → 💾 Save → name it.',
      'To restore: 📂 Load → pick it from the list.',
      'Before anything drastic, use 📂 Load → Export to file and keep the JSON somewhere safe.',
      'A config with embedded background photos can outgrow browser storage — if it warns you, use the file export.',
    ],
  },
  {
    id: 'native',
    title: 'Show media players, locks, fans and vacuums',
    body: ['The card does not draw these itself; it can embed Home Assistant\'s own controls for them.'],
    steps: [
      'Design → Tiles (Global scope) → turn on Native controls.',
      'It is off by default because each one embeds a native element, which costs render time on a large media fleet.',
      'The controls appear as the "Native controls" block on the default tile style.',
    ],
  },
  {
    id: 'views',
    title: 'Split a big dashboard into views',
    body: ['Views are tabs inside the card, each with its own filter and layout — useful once one scrolling wall stops being readable.'],
    steps: [
      'Views → Add view, name it, give it an icon.',
      'Filter it by room, device type, or specific devices.',
      'Override columns, tile size or tile style per view if that view needs a different density.',
      'Pin the handful of devices you touch daily with Favourites, and let a view show only those.',
    ],
  },
];

export const HELP_INTRO =
  'How the card fits together. For the exhaustive option list — every key, its scope and its default — see docs/tools/reference.html.';
